#!/usr/bin/env bash
set -euo pipefail

SERVICE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SERVICE_DIR/.." && pwd)"

VLLM_PYTHON="${VLLM_PYTHON:-$SERVICE_DIR/.venv/bin/python}"
VLLM_BRAIN_MODEL="${VLLM_BRAIN_MODEL:-mistralai/Mistral-Small-4-119B-2603-NVFP4}"
VLLM_BRAIN_SERVED_MODEL_NAME="${VLLM_BRAIN_SERVED_MODEL_NAME:-sandy-brain}"
VLLM_BRAIN_HOST="${VLLM_BRAIN_HOST:-127.0.0.1}"
VLLM_BRAIN_PORT="${VLLM_BRAIN_PORT:-8000}"
VLLM_BRAIN_MAX_MODEL_LEN="${VLLM_BRAIN_MAX_MODEL_LEN:-16384}"
VLLM_BRAIN_GPU_MEMORY_UTILIZATION="${VLLM_BRAIN_GPU_MEMORY_UTILIZATION:-0.88}"
VLLM_BRAIN_ATTENTION_BACKEND="${VLLM_BRAIN_ATTENTION_BACKEND:-TRITON_MLA}"
VLLM_BRAIN_REASONING_PARSER="${VLLM_BRAIN_REASONING_PARSER:-mistral}"
VLLM_BRAIN_TOOL_PARSER="${VLLM_BRAIN_TOOL_PARSER:-mistral}"
VLLM_BRAIN_GENERATION_CONFIG="${VLLM_BRAIN_GENERATION_CONFIG:-vllm}"
VLLM_BRAIN_CUDA_VISIBLE_DEVICES="${VLLM_BRAIN_CUDA_VISIBLE_DEVICES:-GPU-5b44da3f-50e1-6622-bd78-8382819e596d}"

export CUDA_DEVICE_ORDER="${CUDA_DEVICE_ORDER:-PCI_BUS_ID}"
export CUDA_VISIBLE_DEVICES="$VLLM_BRAIN_CUDA_VISIBLE_DEVICES"
export VLLM_USE_FLASHINFER_SAMPLER="${VLLM_USE_FLASHINFER_SAMPLER:-0}"

cd "$ROOT_DIR"

exec "$VLLM_PYTHON" -m vllm.entrypoints.cli.main serve "$VLLM_BRAIN_MODEL" \
  --served-model-name "$VLLM_BRAIN_SERVED_MODEL_NAME" \
  --host "$VLLM_BRAIN_HOST" \
  --port "$VLLM_BRAIN_PORT" \
  --max-model-len "$VLLM_BRAIN_MAX_MODEL_LEN" \
  --gpu-memory-utilization "$VLLM_BRAIN_GPU_MEMORY_UTILIZATION" \
  --attention-backend "$VLLM_BRAIN_ATTENTION_BACKEND" \
  --generation-config "$VLLM_BRAIN_GENERATION_CONFIG" \
  --reasoning-parser "$VLLM_BRAIN_REASONING_PARSER" \
  --tool-call-parser "$VLLM_BRAIN_TOOL_PARSER" \
  --enable-auto-tool-choice
